bank-gate:
  image: your/bank-gate-emulator
  ports:
    - "9999:9999"

mysql:
  image: mysql:8.0
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app

postgres:
  image: postgres:14
  environment:
    POSTGRES_PASSWORD: root
    POSTGRES_DB: app
